### ISSUE TITLE
[Hawthorn] Active link color of "Syllabus" page is blue, not orange

### ISSUE THREAD

**Issue by jeremyosborn** [gymnasium/tracker#104] opened 2020-11-05 20:56 UTC
When on the Syllabus page (looks like this issue is for all the courses) the active link is blue not orange

https://courses.gymnasium.dev/courses/GYM/104/0/info

<img width="668" alt="Screen Shot 2020-11-05 at 3 52 09 PM" src="https://user-images.githubusercontent.com/6589523/98295327-6920d880-1f7f-11eb-940a-6b6bf419c1a3.png">

**Comment by mbifulco** [comment] 2020-11-06 00:17
Duplicate of #93 - I'll track it there.  Good catch!

**Closed by mbifulco** 2020-11-06 00:17 UTC
Labels: :bug: bug, :deciduous_tree: Hawthorn QA
